os:
- windows
- linux
- osx
language: rust
rust:
- 1.46.0
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
  - "/^rust-.*/"
jobs:
  include:
  - name: compile for linux
    os: linux
    script: scripts/compile.linux.sh
    if: tag IS present
    deploy:
      provider: releases
      api_key: &1
        secure: u7hR35HSbToyFLSCATccMc37Vkm5hraLV1n0ExbdeXx9Ipq/oQpt5ABTMVoKi/Zc/N88Vt90ltAPQ2mlE0n6GcTT0OR0bancZ6FclFOQM4jTBJNP4c9rHmfo2RdzqQU5ji5SuW87W7KoAgxL/c7kmVpLrBlEjALKfqtRd82AvDX+BZ4ryXXr+1qBj06T8slCYNWOEpLDFzE03AaOdidCOf374oymBlP6UjW0/3XihUycfhoGJ5Qr7FS5BB65NFXk/QgLvaHYfifeIyHaydHDuswGXYKAiTYwQ1my/+n25gMRq7xjt/XAXVPaajWYtsCLQxxbpI1a5SeTpf0A+MuCUJHJkeN2QX3qiWtByHvIJ1QFgkh2M2iobSOQdEfyCgc3wwH7Hp+2KrKOEVIJcfehcI8uXjU6ZDLJYOO/IZG0o6EVU2XQJxFBP+AA/SZReRHsXMjBLK3m4Be6kJN561RnfJnpCJl/oR72ZoeRFMyX0r5bZkorT17o1SWC4smxulDHfgVFCR9vAUnMH4s9BPXMV1Ndzgl26Y1Y7YaU9awD0URSDX43m5Q4FOYw3jFUs3opPsAwXj9LOnZDNwuWxubbEm2NQQgaC/ZGXH6GGJKuGrWXHvXvJOayzaOmfvgAIFGV28wYsvgxe7/E6KhZMMKPu4kb7atV5xbctZI9YmQLNQI=
      draft: true
      skip_cleanup: true
      overwrite: true
      file: track.linux
      on: &2
        tags: true
  - name: compile for macos
    os: osx
    script: scripts/compile.mac.sh
    if: tag IS present
    deploy:
      provider: releases
      api_key: *1
      draft: true
      skip_cleanup: true
      overwrite: true
      file: track.macos
      on: *2
  - name: compile for windows
    os: windows
    script: scripts/compile.windows.sh
    if: tag IS present
    deploy:
      provider: releases
      api_key: *1
      draft: true
      skip_cleanup: true
      overwrite: true
      file: track.windows.exe
      on: *2
