[package]
name = "track-cli"
version = "0.1.0"
authors = ["Jethro Kuan <jethrokuan95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.2"
dirs = "3.0"
chrono = "0.4.19"
